# Base configs
baseurl: "https://bastianphoto.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Kim Bastian"
subtitle: "See the world through my eyes!"
author: "Kim Bastian"
header:
 title: "Photography"
 subtitle: "by Kim Bastian"
footer:
 name: "Kim Bastian:"
 bio: "I am an amateur/hobby photographer from Copenhagen. When I'm not working as a civil engineer I like to take pictures of everything from landscapes, urban/street, to portrait and travel photography. If you want your picture taken contact me and lets have a talk."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/kim.bastian"
  instagram: "https://www.instagram.com/kim.bastian"
